### ISSUE TITLE
Dropdown List Unreadable

### ISSUE THREAD

**Issue by rawkode** [tjkohli/nebula-ui#10]
Hey,

Awesome work! There's a minor problem though, the menubar's are impossible to read. Screenshot attached.

Thanks

![screen](https://cloud.githubusercontent.com/assets/145816/22428227/2b7f05d2-e6fe-11e6-9561-ad02d1b82aff.png)

**Comment by tjkohli** [comment]
@rawkode Can you provide more information?
What operating system are you using?
Are you using [nebula-syntax](https://github.com/tjkohli/nebula-syntax/) as well?

**Comment by rawkode** [comment]
Hi @tjkohli,

Linux:
Atom    : 1.13.1
Electron: 1.4.15
Chrome  : 53.0.2785.143
Node    : 6.5.0

I've switched syntax multiple times, between Base16, Nebula and Firewatch. All experience this problem.

**Comment by tjkohli** [comment]
@rawkode What distro of Linux do you have? I just tested on Linux Mint and it seems fine:
![Linux Mint Atom with nebula-ui theme](http://tjkoh.li/T8jq/2uILWW89+)

What happens if you use other UI themes?

**Comment by rawkode** [comment]
Ack, I'm really sorry! Other themes have the same problem.

Must be something else I've installed or changed recently.

**Comment by tjkohli** [comment]
No worries :) I hope you get it resolved
