### ISSUE TITLE
Git-Plus Stage Files Dropdown Missing Status Indicator

### ISSUE THREAD

**Issue by dvigne** [tjkohli/nebula-ui#11]
@tjkohli First of all, I love the theme! Wonderful job! I shared it with my team of developers who also use it now! I noticed one small issue where if you use the package git-plus and try to stage files, the check mark to indicate whether a file has been staged is missing. I have attached the screenshots below and a possible solution written in plain css. I could submit a PR if it would help. Thanks!

## Solution
```
.select-list ol.list-group.mark-active li.active:before, .select-list ol.list-group.mark-active li.active:before, .select-list ol.list-group.mark-active li.selected:before {
    margin-right: 0.45454545em;
    color: #73c990;
}

.select-list ol.list-group.mark-active li.active::before, .select-list ol.list-group.mark-active li.active::before {
    font-family: 'Octicons Regular';
    font-weight: normal;
    font-style: normal;
    display: inline-block;
    line-height: 1;
    -webkit-font-smoothing: antialiased;
    text-decoration: none;
    font-size: 14px;
    width: 14px;
    height: 14px;
    content: "\f03a";
}
.list-group .selected::before, .list-tree .selected::before {
    position: relative !important;
}
```

### Before
![no_check](https://cloud.githubusercontent.com/assets/16086309/22452957/0eb0dba6-e749-11e6-9759-4747e8d0af51.PNG)
### After
![check](https://cloud.githubusercontent.com/assets/16086309/22452956/0ead2d8a-e749-11e6-9792-05d9f693e747.PNG)

**Comment by tjkohli** [comment]
Hi @dvigne!

Thank you for the well-thought out post. I actually released [0.5.0](https://github.com/tjkohli/nebula-ui/releases/tag/v0.5.0) which added support for the Git-plus package.

Update it and let me know if that works better for you!

**Comment by dvigne** [comment]
Looks fantastic and works great! Thank you for the quick reply!

Cheers,
Derick

**Comment by tjkohli** [comment]
@dvigne Nebula is still pretty new, only 11 days old, so please spread the word if you love it! It'll help keep it going.

**Comment by dvigne** [comment]
@tjkohli Absolutely! Honestly, at least in my case, it made Atom way more efficient...cleaner interface I suppose, but I've been sharing it with friends and they seem to love it.
