### ISSUE TITLE
Tip: Atom Styleguide

### ISSUE THREAD

**Issue by Gert-dev** [tjkohli/nebula-ui#12]
Hello

I just wanted to leave a tip about the Atom styleguide here, in case you haven't heard of it. If you have the default Atom styleguide package enabled, you can open the styleguide via `Packages` → `Styleguide` → `Show`.

The styleguide allows you to see a rough overview of how everything looks in the UI theme. For example, I notice that the toggle button's bubble appears to be outside of the button itself. I can't decide if the progress bar is unstyled or purposefully styled as it currently is :P. The checklist check marks you already fixed earlier are also in here, so they now show up nicely!

Thanks for your work and attention to detail in this theme! Feel free to close this ticket as soon as you've read it.

**Comment by tjkohli** [comment]
@Gert-dev Thanks! I am aware of (and use) the Styleguide. I tend to focus more on designing & styling for real-world usage of the theme rather than just creating a "skin" because Nebula is more than just another skin. It's made to help you be more productive in Atom.
