### ISSUE TITLE
Atom restart button issue

### ISSUE THREAD

**Issue by onetrev** [tjkohli/nebula-ui#17]
Looks to me there is a colour issue for the text on the restart button. It displays on hover, but it's invisible until then. Otherwise, just wanted to say thanks, I love the UI and theme, very pro and love the UX focus!

![snip_20170214114048](https://cloud.githubusercontent.com/assets/597601/22910145/2aad6a54-f2ac-11e6-96b0-03e9e6f94f8f.png)

**Comment by tjkohli** [comment]
Fixed. Thanks for reporting @onetrev! It will be released with 0.6.0 soon.

Spread the word if you like the theme! It will help me make it better.

**Comment by onetrev** [comment]
Awesome, thank you! And I am definitely trying to spread the word as it very much deserves to be spread.

**Comment by tjkohli** [comment]
Thank you 🙏🏼
