### ISSUE TITLE
Another Type (font) option

### ISSUE THREAD

**Issue by onetrev** [tjkohli/nebula-ui#18]
Just wondered if in the ReadMe it might be handy to list another font option in the **Type** section since SF Mono is not available for those outside of Mac? Especially when you consider Windows is the biggest user base of Atom? Personally I would say [Fira Code](https://github.com/tonsky/FiraCode) (or at least Fira Mono) is pretty nice too. 

I really think the programming ligatures in Fira Code are really slick, and fit in well with your fantastic clean theme goals of legibility, making it easier to focus, etc.

**Comment by tjkohli** [comment]
@onetrev Feel free to use whatever font you'd like. I recommend SF Mono, and that's what it'll always be. A recommendation.

**Comment by onetrev** [comment]
Sorry, just thought might be useful to also include a suggestion for the majority of users who can't actually use the suggested font. :)   No worries! Thanks for the follow up.

**Comment by tjkohli** [comment]
@onetrev You have a point, however the Mac platform is the recommended platform for this theme. Looks best in it :)
