### ISSUE TITLE
Add tool-bar package to Focus Mode

### ISSUE THREAD

**Issue by onetrev** [tjkohli/nebula-ui#19]
Would it be possible to also fade out (Focus Mode) the very popular [Atom Tool Bar](https://atom.io/packages/tool-bar) package until it's hovered? Similar to how the file explorer and mini map and such are faded that is? Thanks!!

**Comment by tjkohli** [comment]
I got to adding support for this plugin, however it seems to be [dead](https://github.com/suda/tool-bar/issues/204). It does not work with any theme, period. I am closing this "issue" until further notice. Thanks!
