### ISSUE TITLE
Scroll bars are unstyled on Ubuntu 16.04

### ISSUE THREAD

**Issue by rnyberg** [tjkohli/nebula-ui#2]
In Atoms built in themes the scroll bars for tree view/code view are small and stylished. With your theme I seem to be getting the huge and ugly default scroll bars that Chromium sports.

**Comment by tjkohli** [comment]
Hmmmm. Can you post a screenshot? I'll get this fixed ASAP.

**Comment by rnyberg** [comment]
Album with One Dark vs Nebula http://imgur.com/a/HWi1K

**Comment by tjkohli** [comment]
Thanks @rnyberg! Styled scroll bars coming super soon.

**Comment by tjkohli** [comment]
@rnyberg Try updating to 0.2.1 😉

**Comment by rnyberg** [comment]
I'll test tomorrow. Thanks for the fast fix.

**Comment by tjkohli** [comment]
@rnyberg Do they work well for you now?

**Comment by rnyberg** [comment]
Yes
