### ISSUE TITLE
Font became rather horrible since Cantarell update (Linux)

### ISSUE THREAD

**Issue by Gert-dev** [tjkohli/nebula-ui#20]
Four days ago, the official GNOME (Linux desktop environment) font [Cantarell](https://github.com/GNOME/cantarell-fonts) had a new release where they apparently redesigned it from scratch to interpolate better in bold settings. Next to this needing some adjustment from my part - as it always does when your base font changes 😄 -, it now looks rather horrendous in nebula-ui, for some reason:

![with font-weight](https://user-images.githubusercontent.com/24809863/36112088-bee9f8be-1028-11e8-836b-e7a533b0fa02.png)

As you can see here, the font is incredibly thin and hard to read, even when hovering over it (which lights up the font due to focus). This must be due to the Cantarell update, since it worked fine before.

I opened up the developer tools and played with the nebula-ui settings a bit and it turns out the culprit is the [`font-weight: 300` setting](https://github.com/tjkohli/nebula-ui/blob/9dc0b3d5a23738823564886793540f0b6609c4c6/styles/base.less#L8). Disabling it makes the font look normal again, for example:

![without font-weight](https://user-images.githubusercontent.com/24809863/36112085-bbe29770-1028-11e8-93ef-bd8737b2c2f4.png)

I don't know how this will look with other base fonts on Linux, though. I also gave `DejaVu Sans Book` a whirl, since I think `DejaVu` is another commonly used font on Linux desktops, and it also benefits from removing the font-weight and experiences thinness with it enabled. Perhaps it would be prudent to just disable it for the Linux platform entirely?

**Comment by tjkohli** [comment]
Hi @Gert-dev, thanks for the note and thanks for proposing a solution. I recommend adding this override in your personal CSS file with an !important and it should work for you. I do not have a Linux instance to play around with at the moment so I won't be fixing this anytime soon.

**Comment by Gert-dev** [comment]
@tjkohli That does indeed do the trick.

I understand that time can be a constraint. In any case other visitors will know what's going on and have a workaround handy.

Thanks!
