### ISSUE TITLE
Padding/margin in tree view

### ISSUE THREAD

**Issue by Gert-dev** [tjkohli/nebula-ui#4]
Hello

I've yet to take this theme for a good test drive in the near future, but wanted to report a small thing I noticed after firing it up for the first time. Could it be that there is a small lack of padding/margin in some area's? Take the following screenshot, for example:

![screenshot](https://cloud.githubusercontent.com/assets/24809863/22398752/d5cfac4c-e58e-11e6-8d83-e6a2bbe0b4af.png)
 
The minor detail I'm referring to is in the left corner of the selected item from the tree view, bordered on the "expando" or arrow icon. The highlighting color seems to stob very abruptly at the expando itself. Also, it appears that the expando is not centered in the highlighting, but positioned higher than the center.

Just a very minor detail, but wanted to let you know anyway :-).

I'm using Linux, in case this is specific to Atom on Linux.

Thanks in advance

**Comment by tjkohli** [comment]
Thanks, @Gert-dev!

The issue has been fixed.
It will be released alongside in 0.4.4 with another fix, hopefully today or tomorrow. :)
