### ISSUE TITLE
Tab and status bar padding improvements

### ISSUE THREAD

**Issue by WoodyWoodsta** [tjkohli/nebula-ui#5]
Three cheers for a well produced and innovative theme! I like the concepts around focus mode and the in-editor interactivity. This is what the web-platform is capable of doing!

Just two minor padding issues (over and above those in the tree view):

- For the neglected crowd on Linux, who do not have the luxury of MacOS's inline title-bar, there is no padding between the tab and the title bar, which 99% of the time will be a different color to the tab background. This makes the vertical alignment of the tabs, especially when hovering over one, a little awkward:

  ![image](https://cloud.githubusercontent.com/assets/8268040/22403732/0c040e94-e629-11e6-8dea-24aa41352399.png)

- I also thought that the status bar could do with some top padding to, again, reduce the vertical alignment awkwardness:

  ![image](https://cloud.githubusercontent.com/assets/8268040/22403741/56cd00d4-e629-11e6-8c62-d4b9667e231a.png)

Just my thoughts!

**Comment by tjkohli** [comment]
Thanks for the feedback. Update to 0.4.4 and let me know how it looks.

https://github.com/tjkohli/nebula-ui/releases/tag/v0.4.4

**Comment by WoodyWoodsta** [comment]
Tabs look great! Status bar is better! Thank you.
