### ISSUE TITLE
Error message styling in README?

### ISSUE THREAD

**Issue by Gert-dev** [tjkohli/nebula-ui#6]
Hello

Thanks for fixing the padding issues so quickly, it being missing tarnished an otherwise visually very impressive theme :-).

I'm drawn to the screenshot in the README that shows error messages pulsing with animation, but can't seem to achieve that with my error linting - I still get the ol' squiggly lines. Is this something I have to configure or perhaps not compatible with all languages? I'm currently using the widely used linter package to display PHP errors inside the editor.

In case it's helpful, I think it's [this line](https://github.com/steelbrain/linter-ui-default/blob/master/styles/linter-ui.less#L82) that's handling the styling of the messages in the editor for the linter package.

Thanks in advance

**Comment by tjkohli** [comment]
@Gert-dev Are you using [Nebula Syntax](https://github.com/tjkohli/nebula-ui)?

**Comment by Gert-dev** [comment]
I am, yes :).

**Comment by tjkohli** [comment]
No worries! I'm looking into this and assure you, will get the best solution out soon.
