### ISSUE TITLE
Missing styling for checked items in lists

### ISSUE THREAD

**Issue by Gert-dev** [tjkohli/nebula-ui#8]
Hello

I just noticed that list views that contain selectable items seem to have no checkmark styling.

An example of a plugin using these is git-plus in its `Stage Files` view. Here, you can press the return key to select the file to stage. In One Dark and other styles, a checkmark will appear in front of the row in the list. It also appears that other themes reserve space for this checkmark so that the item doesn't jump to the right when the item is selected.

The class hierarchy for this is (from top to bottom)

* `div class="select-list"`
  * `ol class="list-group mark-active"`
    * `li class="selected active"`, here, `selected` means that the row is currently selected with the arrow keys, which is already styled. `active` means that the item is also checked and is not present if it isn't, this currently isn't styled so there is no distinction between checked and unchecked items.
      * The contents of the row

Thanks in advance

**Comment by tjkohli** [comment]
Thanks, @Gert-dev! If I understand correctly, this request is related to the [git-plus plugin](https://atom.io/packages/git-plus)?
I'll consider adding support to them strictly on a popularity basis.

**Comment by Gert-dev** [comment]
Thanks! It is indeed related to git-plus, but I believe it originates from the atom-space-pen-views library, which is used by other packages as well (I referenced git-plus because it happens to be using these).

**Comment by tjkohli** [comment]
Oh look what we have here! 😉

![Nebula Git-plus stage files view](http://tjkoh.li/db1U/1dPIs9te+)

Coming soon, in 0.5.0.

**Comment by tjkohli** [comment]
Fixed! Update to 0.5.0 :)
