### ISSUE TITLE
White text only

### ISSUE THREAD

**Issue by khipukamayuq** [tjkohli/nebula-ui#9]
Downloaded theme and syntax via Atom's Installer in the Settings Menu. After setting theme and syntax to Nebula I only get white text. Same in all fonts I tried; other themes/syntax unaffected. OS is Linux Mint Cinnamon 17.3.

**Comment by tjkohli** [comment]
Can you post a screenshot?

**Comment by khipukamayuq** [comment]
![screenshot from 2017-01-29 17 12 39](https://cloud.githubusercontent.com/assets/16020142/22408402/420b76c2-e646-11e6-910b-3c9e79c34b90.png)
![screenshot from 2017-01-29 17 12 12](https://cloud.githubusercontent.com/assets/16020142/22408407/494350d6-e646-11e6-90b3-d2f2a1d341c5.png)

Hope this helps. Thanks!

**Comment by tjkohli** [comment]
@khipukamayuq That does help! But I am confused. I did a fresh install of Linux Mint (linuxmint-18.1-cinnamon-64bit) in Parallels and installed Atom 1.13.1 x64 via Dev, installed the latest nebula-ui and syntax, and made an HTML file (as per your screenshot) and this is what I see:

![screenshot](http://tjkoh.li/5L4f/12Vp4jIn)

**Comment by khipukamayuq** [comment]
Dammit. I got it. It was all me. New to Atom and Linux both. I didn't know Atom wasn't upgrading from my CLI commands. I was on 1.7.3. Upgraded to 1.13.1 and everything is fine. Thanks for your trouble, though! Looks beautiful!!

**Comment by tjkohli** [comment]
Glad to hear that!! Enjoy it.
